// app/components/SummaryDisplay.tsx
export default function SummaryDisplay({ summary }: { summary: string }) {
  return (
    <div className="mt-4 p-4 border rounded-lg bg-gray-100 dark:bg-gray-800">
      <h2 className="text-xl font-bold">Summary:</h2>
      <p className="mt-2">{summary}</p>
      <button
        onClick={() => navigator.clipboard.writeText(summary)}
        className="mt-2 px-3 py-1 bg-green-500 text-white rounded-md"
      >
        Copy to Clipboard
      </button>
    </div>
  );
}

// vite-project/src/components/SummaryDisplay.vue
<template>
    <div v-if="summary" class="card bg-base-200 p-4 w-full max-w-2xl">
      <h2 class="text-lg font-bold">Summary</h2>
      <p>{{ summary }}</p>
      <button class="btn btn-secondary mt-2" @click="copyToClipboard">Copy to Clipboard</button>
      <a :href="url" target="_blank" class="link mt-2">Original Review</a>
    </div>
  </template>
  
  <script setup lang="ts">
  import { ref, defineProps } from 'vue';
  
  const props = defineProps<{ summary: string; url: string }>();
  const copyToClipboard = () => navigator.clipboard.writeText(props.summary);
  </script>
