// app/components/URLInput.tsx
import { useState } from 'react';
import { fetchSummary } from '../utils/api';

export default function URLInput({ onSummary }: { onSummary: (summary: string) => void }) {
  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async () => {
    if (!url) return alert('Please enter a URL.');

    setLoading(true);
    try {
      const summary = await fetchSummary(url);
      onSummary(summary);
    } catch {
      alert('Error fetching summary.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col items-center gap-2">
      <input
        value={url}
        onChange={(e) => setUrl(e.target.value)}
        placeholder="Paste product review URL"
        className="w-full p-2 border rounded-md"
      />
      <button
        onClick={handleSubmit}
        className="px-4 py-2 bg-blue-500 text-white rounded-md"
        disabled={loading}
      >
        {loading ? 'Summarizing...' : 'Summarize'}
      </button>
    </div>
  );
}

// vite-project/src/components/UrlInput.vue
<template>
    <div class="flex flex-col items-center gap-4 w-full max-w-lg">
      <input
        v-model="url"
        class="input input-bordered w-full"
        placeholder="Enter product review URL"
        @keyup.enter="handleSubmit"
      />
      <button class="btn btn-primary w-full" @click="handleSubmit" :disabled="loading">
        {{ loading ? 'Summarizing...' : 'Summarize' }}
      </button>
    </div>
  </template>
  
  <script setup lang="ts">
  import { ref, defineEmits } from 'vue';
  import { fetchSummary } from '../services/api';
  
  const url = ref('');
  const loading = ref(false);
  const emit = defineEmits(['summaryGenerated']);
  
  const handleSubmit = async () => {
    if (!url.value) {
      alert('Please enter a valid URL.');
      return;
    }
  
    loading.value = true;
    try {
      const summary = await fetchSummary(url.value);
      emit('summaryGenerated', { summary, url: url.value });
    } catch (error) {
      alert('Error fetching summary. Please try again.');
    } finally {
      loading.value = false;
    }
  };
  </script>
